# NumPy - Exercises

## NumPy - 1st Exercise

Given two vectors $a$ and $b$, compute $((a+b)*(-a/2))$ without creating any copies, i.e. by exclusively using in-place operations.

In [22]:
import numpy as np


a = np.full(10, 6.0)
b = np.full(10, 18.0)
print(a)
print(b)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
[18. 18. 18. 18. 18. 18. 18. 18. 18. 18.]


#### Solution Proposal

In [23]:
import numpy as np


a = np.full(10, 6.0)
b = np.full(10, 18.0)
print(a)
print(b)

np.add(a, b, out=b)
np.divide(a, 2.0, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)
print(a)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
[18. 18. 18. 18. 18. 18. 18. 18. 18. 18.]
[-72. -72. -72. -72. -72. -72. -72. -72. -72. -72.]


## NumPy - 2nd Exercise

Given a random 10x2 matrix that represents cartesian coordinates, convert them to polar coordinates.

__HINTS__: Use `np.arctan2` and $(r, \varphi) = (\sqrt{x^2 + y^2}, \arctan{\frac{y}{x}})$.

In [24]:
import numpy as np


pts = np.random.random((10, 2))

#### Solution Proposal

In [25]:
import numpy as np


pts = np.random.random((10, 2))

xs = pts[:,0]
ys = pts[:,1]
r = np.sqrt(xs**2 + ys**2)
phi = np.arctan2(ys, xs)
print(r)
print(phi)

[1.03002096 0.97664995 1.06368085 0.76390283 0.50819685 0.79887796
 0.89780071 0.09941149 1.06447049 1.04375398]
[1.26574704 0.65357064 1.14039322 1.45495252 0.85446572 0.30560653
 0.7415068  1.16005112 0.36184602 0.925016  ]


## NumPy - 3rd Exercise

Define a ufunc that checks whether a given number is square and apply it to the array `nums`, then use the resulting boolean array as a mask to show only the square numbers from `nums`.

__HINTS__: Use `np.frompyfunc` and `np.ndarray.astype`.

In [26]:
import numpy as np


nums = np.arange(100)

def square(x):
    return False

#### Solution Proposal

In [27]:
import numpy as np


nums = np.arange(100)

def square(x):
    return (x**(1/2)).is_integer()
 
ufunc_square = np.frompyfunc(square, 1, 1)
square_nums_mask = ufunc_square(nums).astype(bool)

print(nums)
print(nums[square_nums_mask])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  4  9 16 25 36 49 64 81]


## NumPy - 4th Exercise

The midpoint Riemann sum gives a simple approximation for an integral. Compute this approximation for the sine function over the intervall [$0$, $2\pi$] with the resolution `dx`.

$\int_{a}^b f(x)dx = \sum\limits_{i=0}^n f(\frac{x_i + x_{i-1}}{2}) \Delta x$ with $x_0 = a, x_n = b$

In [28]:
import numpy as np


dx = 0.001
xs = np.arange(0, 2*np.pi, dx)

#### Solution Proposal

In [29]:
import numpy as np


dx = 0.1
xs = np.arange(0, 2*np.pi, dx)

xsm = (xi[1:] + xi[:-1]) / 2
rs = np.sum(np.sin(xi) * dx)

print(f"Riemann sum over [{0}, 2pi]: {rs:.6f}")

Riemann sum over [0, 2pi]: -0.000699


## NumPy - 5th Exercise

* First create two random, symmetric matrices $A_s$ and $B_s$, then
* compute the matrix product $C$ of $A_s$ and $B_s$, then
* compute the eigenvalues of $C$, and finally 
* compute the determinante of $C$.

__HINTS__: $A_s = A + A^T$ gives you a symmetric matrix from $A$.

In [30]:
import numpy as np


A = np.random.random((5, 5))
B = np.random.random((5, 5))

#### Solution Proposal

In [32]:
import numpy as np


A = np.random.random((5, 5))
B = np.random.random((5, 5))
As = A + A.T
Bs = B + B.T
C = np.matmul(As, Bs)
eigs = np.linalg.eigvals(C)
det = np.linalg.det(C)

print(f"C = {C}")
print(f"eigs(C) = {eigs}")
print(f"det(C) = {det}")

C = [[6.55758569 6.08903394 4.74339947 4.4773704  7.23213939]
 [3.90229503 3.55158646 2.89236803 1.86948116 5.06070868]
 [6.42323036 4.59659897 4.71098187 3.47911565 6.36990692]
 [5.9612812  5.60764753 4.5171865  3.9059854  7.77199224]
 [5.63776579 3.5867468  4.1315447  2.79413242 5.58567229]]
eigs(C) = [24.11231638+0.j         -0.09275176+1.12428579j -0.09275176-1.12428579j
  0.04549555+0.j          0.33950332+0.j        ]
det(C) = 0.4739702276748588


## NumPy - 6th Exercise

Finite differences can be used to compute numerical derivatives. Use this to approximate the derivative of te sine function over the intervall [$0$, $2\pi$] with the resolution `dx` and compare this against the cosine. Finally, compute the [root-mean-square error](https://en.wikipedia.org/wiki/Root-mean-square_deviation) of these functions.

$f'(x_i) = \frac{f(x_i + \Delta x) - f(x_i - \Delta x)}{2 \Delta x}$

In [33]:
import numpy as np


dx = 0.001
xs = np.arange(0, 2*np.pi, dx)

#### Solution Proposal

In [34]:
import numpy as np


dx = 0.1
xi = np.arange(0, 2*np.pi, dx)

fxi = np.sin(xi)
df = (fxi[2:] - fxi[:-2]) / (2.0*dx)

fcmp = np.cos(xi[1:-1])
rmse = np.sqrt(np.mean((df - fcmp)**2))
print(f"RMSE = {rmse}")

RMSE = 0.001160232964046785
